import type { CardGroup, TarotCard } from "./types";

const groupMeta: Record<CardGroup, { category: string; accentColor: string }> = {
  major: { category: "大牌", accentColor: "#8f63ff" },
  chip: { category: "芯片组", accentColor: "#4fd9ff" },
  battery: { category: "电池组", accentColor: "#b9f56f" },
  laser: { category: "激光剑", accentColor: "#ff5a5a" },
  disk: { category: "硬盘币", accentColor: "#c89b54" },
  easter: { category: "角色彩蛋", accentColor: "#f7b267" }
};

type CardSeed = Omit<TarotCard, "category" | "accentColor" | "imageUrl" | "isPublished"> & {
  category?: string;
  accentColor?: string;
};

const makeCard = (card: CardSeed): TarotCard => ({
  ...card,
  category: card.category ?? groupMeta[card.group].category,
  accentColor: card.accentColor ?? groupMeta[card.group].accentColor,
  imageUrl: "",
  isPublished: true
});

export const initialCards: TarotCard[] = [
  makeCard({
    id: "major-01",
    order: 1,
    name: "体验版用户",
    subtitle: "你不是勇敢，你是没看协议。",
    group: "major",
    tags: ["测试", "冲动", "试错", "未阅读协议"],
    uprightMeaning: "勇敢尝鲜、无知无畏、愿意开始。",
    reversedMeaning: "乱点按钮、轻信新东西、总当小白鼠。",
    aiKeywords: ["测试", "冲动", "试错", "未阅读协议"],
    stageLine: "你的人生最大优点是勇敢，最大缺点是每次勇敢都没看说明书。",
    description: "别人探索世界靠理性，你探索世界靠手快。你的很多开始不是规划出来的，而是误触出来的。",
    imageElements: ["同意按钮", "弹窗", "测试版标签", "数据深渊"],
    visualStyle: "愚者踏空式构图，蓝紫底色，高亮青白按钮。"
  }),
  makeCard({
    id: "major-02",
    order: 2,
    name: "提示词工程师",
    subtitle: "你最强的能力，是把没做的事说得像快做完了。",
    group: "major",
    tags: ["会说", "会写", "控制输出", "包装"],
    uprightMeaning: "表达能力强、会调动资源、善于包装。",
    reversedMeaning: "空话太多、擅长描述不擅长落地。",
    aiKeywords: ["会说", "会写", "控制输出", "嘴替型人才"],
    stageLine: "你不是没有能力，你是把 70% 的能力都用来描述自己很有能力。",
    description: "你的核心竞争力不是执行，而是描述执行。你一张嘴，空气里都飘着方向已经很清晰了。",
    imageElements: ["悬浮键盘", "词语法阵", "token 流", "光标"],
    visualStyle: "现代法师感，电蓝与金属银，文字像能操控现实。"
  }),
  makeCard({
    id: "major-03",
    order: 3,
    name: "黑箱模型",
    subtitle: "结果出来了，过程最好别问。",
    group: "major",
    tags: ["神秘", "不可解释", "置信度", "洞察"],
    uprightMeaning: "直觉强、神秘、有洞察。",
    reversedMeaning: "不可解释、让人不安、结果全靠玄学。",
    aiKeywords: ["不透明", "神秘", "看不懂", "但好像有点准"],
    stageLine: "你最近像个高级模型，大家都觉得你有东西，但没人知道你到底在算什么。",
    description: "你有答案，也有气场，但你没有解释。别人信你，不是因为你透明，而是因为你说得坚定。",
    imageElements: ["黑色立方体", "输入箭头", "输出箭头", "置信区间"],
    visualStyle: "极简神秘，黑色实体透出数据裂纹。"
  }),
  makeCard({
    id: "major-04",
    order: 4,
    name: "产品经理",
    subtitle: "你没有在生活，你在给生活提需求。",
    group: "major",
    tags: ["需求", "迭代", "协调", "反复修改"],
    uprightMeaning: "整合能力强、能发现需求、会推动协作。",
    reversedMeaning: "需求泛滥、过度干预、自己都不知道要什么。",
    aiKeywords: ["需求", "迭代", "协调", "反复修改"],
    stageLine: "你的人生最大问题是：别人都在活，你在给生活提需求。",
    description: "你对现状最大的态度不是接受，是这里是不是还可以优化一下。",
    imageElements: ["便签王座", "流程图", "原型框", "评论气泡"],
    visualStyle: "丰饶的是需求，酒红与科技蓝，信息密度略高。"
  }),
  makeCard({
    id: "major-05",
    order: 5,
    name: "系统管理员",
    subtitle: "你想要的不是爱，是权限。",
    group: "major",
    tags: ["规则", "权限", "安全感", "秩序"],
    uprightMeaning: "稳定、控制力强、守住边界。",
    reversedMeaning: "控制欲、死板、权限焦虑。",
    aiKeywords: ["规则", "权限", "安全感", "秩序"],
    stageLine: "你最想要的不是爱情，是确定自己在这段关系里有管理员权限。",
    description: "关系里最让你痛苦的不是冷淡，是权限不明。你希望世界稳定运行，也希望 root 在你手里。",
    imageElements: ["服务器王座", "权限钥匙", "监控面板", "锁与盾牌"],
    visualStyle: "冷、稳、强控制感，深蓝黑与红灯点缀。"
  }),
  makeCard({
    id: "major-06",
    order: 6,
    name: "开源协议",
    subtitle: "你看起来很自由，其实全是条款。",
    group: "major",
    tags: ["合作", "条款", "自由", "责任"],
    uprightMeaning: "共享、信任、共同建设。",
    reversedMeaning: "边界不清、被白嫖、贡献与收益失衡。",
    aiKeywords: ["合作", "条款", "自由", "责任"],
    stageLine: "你看上去很大方，但你内心其实很想给每段关系都附一个使用协议。",
    description: "你愿意共享，但不愿白给。现代人的善良，最好都附带许可证。",
    imageElements: ["协议卷轴", "开源印章", "规则链条", "LICENSE"],
    visualStyle: "宗教仪式感，教皇牌的科技法律版。"
  }),
  makeCard({
    id: "major-07",
    order: 7,
    name: "双系统选择",
    subtitle: "不是选择困难，是哪个都舍不得卸载。",
    group: "major",
    tags: ["选择", "分叉", "适配", "兼容"],
    uprightMeaning: "面临关键选择、两条路都可行。",
    reversedMeaning: "犹豫、兼容性差、脚踩两船。",
    aiKeywords: ["选择", "分叉", "适配", "兼容"],
    stageLine: "你不是感情复杂，你只是人生里同时装了两个系统，现在谁都启动不起来。",
    description: "你想全都要，结果是哪个都跑不稳。你的浪漫不是坚定，而是双开。",
    imageElements: ["启动界面", "两扇入口门", "加载转圈", "兼容性警告"],
    visualStyle: "左右对称，冷暖对照，像系统安装页。"
  }),
  makeCard({
    id: "major-08",
    order: 8,
    name: "自动驾驶",
    subtitle: "车在往前开，你也不知道算不算你开的。",
    group: "major",
    tags: ["前进", "速度", "方向", "失控"],
    uprightMeaning: "推进、加速、目标明确。",
    reversedMeaning: "失控、盲冲、以为自己掌控其实没有。",
    aiKeywords: ["前进", "速度", "方向", "责任归属"],
    stageLine: "你最近的人生开得挺快，就是方向盘到底在谁手里，大家心里都没底。",
    description: "你表面上掌控全局，实际上只是坐得比较直。现代人最擅长高速地失控。",
    imageElements: ["无人车", "自动方向盘", "HUD 路线", "霓虹公路"],
    visualStyle: "战车牌的推进力，强透视与速度感。"
  }),
  makeCard({
    id: "major-09",
    order: 9,
    name: "飞行模式",
    subtitle: "不是高冷，是文明地失踪。",
    group: "major",
    tags: ["断网", "安静", "自闭", "恢复电量"],
    uprightMeaning: "独处、恢复、断联、自我整理。",
    reversedMeaning: "逃避、失联、谁都不想理。",
    aiKeywords: ["断网", "安静", "自闭", "恢复电量"],
    stageLine: "你不是高冷，你只是精神上常年开飞行模式。",
    description: "你最近最适合的社交方式，是谁都别找你。有些独处其实是紧急避险。",
    imageElements: ["飞行模式圣徽", "数字真空", "静音通知", "星轨"],
    visualStyle: "安静留白，深蓝与银灰，比其他牌更空。"
  }),
  makeCard({
    id: "major-10",
    order: 10,
    name: "算法推荐",
    subtitle: "你以为是命运，其实是你太好预测。",
    group: "major",
    tags: ["流量", "偏好", "推送", "循环"],
    uprightMeaning: "趋势、机会、被看见、顺势而为。",
    reversedMeaning: "被操控、重复、越刷越窄。",
    aiKeywords: ["流量", "偏好", "推送", "循环"],
    stageLine: "你以为自己在选择生活，其实生活只是把你最容易上头的那一款不断推给你。",
    description: "系统太懂你，所以把同一种选择、内容和情绪持续推送给你。",
    imageElements: ["信息流瀑布", "兴趣画像", "推荐标签", "后台大手"],
    visualStyle: "被包裹、被喂养、被命中，多层悬浮卡片。"
  }),
  makeCard({
    id: "major-11",
    order: 11,
    name: "审核机制",
    subtitle: "你不是不好，你是没过。",
    group: "major",
    tags: ["通过", "拒绝", "标准", "判分"],
    uprightMeaning: "公平、规则、过滤、边界。",
    reversedMeaning: "压抑、误伤、无情判定。",
    aiKeywords: ["通过", "不通过", "标准", "系统判分"],
    stageLine: "你最近不是运气差，你是被命运判成了疑似低质内容。",
    description: "有时候世界不给你机会，只回一句未予展示。成年人的崩溃没有理由，只有状态。",
    imageElements: ["发光印章", "通过拒绝框", "扫描光束", "评分条"],
    visualStyle: "冷酷垂直，红绿对比，像平台法庭。"
  }),
  makeCard({
    id: "major-12",
    order: 12,
    name: "服务器宕机",
    subtitle: "你不是累，你是暂时不可用。",
    group: "major",
    tags: ["崩溃", "系统故障", "停摆", "精神状态"],
    uprightMeaning: "暂停、强制休息、系统维护。",
    reversedMeaning: "彻底崩溃、全面掉线、无响应。",
    aiKeywords: ["停摆", "死机", "超载", "恢复中"],
    stageLine: "你现在这个状态已经不是累了，是服务暂时不可用。",
    description: "表面上你还坐着，还在回消息，但实际上你的服务已经中断，只是外壳还在线。",
    imageElements: ["服务器塔", "报错红灯", "503 错误", "故障面板"],
    visualStyle: "故障感、glitch、警示红、赛博神谕风。",
    accentColor: "#ff5a5a"
  }),
  makeCard({
    id: "major-13",
    order: 13,
    name: "版本淘汰",
    subtitle: "不是你不行，是旧版本不再维护。",
    group: "major",
    tags: ["下线", "升级", "停更", "替代"],
    uprightMeaning: "更新换代、告别旧我、完成升级。",
    reversedMeaning: "被替代、过时、跟不上变化。",
    aiKeywords: ["下线", "升级", "停更", "不再维护"],
    stageLine: "这不是说你不行，这张牌只是提醒你：旧版本的你已经停止技术支持了。",
    description: "你曾经很好用，只是世界现在需要别的接口。成熟是接受自己不是每个时代的默认配置。",
    imageElements: ["旧系统剥落", "deprecated 标签", "新旧设备", "更新浪潮"],
    visualStyle: "高科技下线的悲壮感，暗金与冷蓝。"
  }),
  makeCard({
    id: "major-14",
    order: 14,
    name: "带宽控制",
    subtitle: "你不是不行，你是同时开太多了。",
    group: "major",
    tags: ["并发", "资源分配", "卡顿", "节制"],
    uprightMeaning: "节制、调配资源、保持平衡。",
    reversedMeaning: "限流、卡顿、精力不够分。",
    aiKeywords: ["并发", "资源分配", "卡", "别同时开太多"],
    stageLine: "你不是能力不够，你是人生后台开太多，CPU 一直在报警。",
    description: "工作、关系、情绪、体面、梦想，个个都在抢网速。很多人的问题不是躺平，而是并发。",
    imageElements: ["数据管道", "限流阀门", "流量计", "任务窗口"],
    visualStyle: "工程结构感，仪表、线条和资源不够分的压迫。"
  }),
  makeCard({
    id: "major-15",
    order: 15,
    name: "信息茧房",
    subtitle: "你不是在获取信息，你是在被养殖。",
    group: "major",
    tags: ["沉迷", "喂养", "回音室", "自我强化"],
    uprightMeaning: "专注、深耕、找到同温层。",
    reversedMeaning: "上瘾、封闭、自我重复。",
    aiKeywords: ["沉迷", "喂养", "回音室", "自我强化"],
    stageLine: "你以为你在获取信息，其实信息在圈养你。",
    description: "最软的牢笼，往往最符合你的兴趣。系统贴心地把同一种情绪喂给你。",
    imageElements: ["半透明信息茧", "短视频碎片", "推荐箭头", "舒适牢笼"],
    visualStyle: "舒服地被困住，粉紫蓝与成瘾的美。"
  }),
  makeCard({
    id: "major-16",
    order: 16,
    name: "数据库删除",
    subtitle: "事后最有用的一句话，永远是你有备份吗。",
    group: "major",
    tags: ["误删", "不可逆", "没备份", "事故"],
    uprightMeaning: "彻底清空、重新开始、断舍离。",
    reversedMeaning: "灾难、失去证据、悔不当初。",
    aiKeywords: ["误删", "不可逆", "没备份", "重大事故"],
    stageLine: "这张牌挺狠，说明你最近表面平静，内心已经像删错正式库一样。",
    description: "有些损失发生时特别安静。没有爆炸，只有一个人盯着屏幕开始怀疑自己。",
    imageElements: ["碎裂数据库", "DELETE 光束", "备份缺失", "屏幕冷光"],
    visualStyle: "不可逆的戏剧性，黑、红、冷白。"
  }),
  makeCard({
    id: "major-17",
    order: 17,
    name: "AI 幻觉",
    subtitle: "错得很稳，也是一种能力。",
    group: "major",
    tags: ["编造", "自信", "逻辑漂移", "想象力"],
    uprightMeaning: "想象力、发散、跳出常规。",
    reversedMeaning: "胡说八道、错得很坚定、自我欺骗。",
    aiKeywords: ["编造", "看似合理", "语气自信", "逻辑漂移"],
    stageLine: "你最近最危险的不是犯错，是你开始相信一个语气很坚定的自己。",
    description: "你的想法越来越像真的，胡说八道也开始拥有结构。现代人的自我欺骗靠措辞。",
    imageElements: ["发光模型头像", "错误图表", "虚高置信度", "扭曲现实"],
    visualStyle: "美、准、假，镜面反射与轻微畸变。"
  }),
  makeCard({
    id: "major-18",
    order: 18,
    name: "系统更新提醒",
    subtitle: "你最大的稳定，就是一直不改。",
    group: "major",
    tags: ["更新", "重启", "拖延", "积压"],
    uprightMeaning: "转折、复盘、重启、必须面对。",
    reversedMeaning: "一拖再拖、永远稍后、问题累积。",
    aiKeywords: ["更新", "重启", "稍后提醒", "积压"],
    stageLine: "命运已经问了你好几次：现在更新吗？你每次都按今晚不方便。",
    description: "该修的 bug 没修，该重启的人生没重启，该面对的问题一直点稍后。",
    imageElements: ["更新弹窗", "稍后按钮", "旧系统卡顿", "通知中心"],
    visualStyle: "幽默压迫感，人物小、通知大。"
  }),
  ...[
    ["chip-ace", 19, "芯片王牌", "刚开机的时候，谁都觉得自己能改变世界。", "新项目启动、强烈行动力、灵感上线。", "刚开头就虚、热情维持很短。", "你最近不是没动力，是刚点着，但烧得像一次性打火机。", "新的想法、新的项目、新的一轮自我感动。还没做，所以什么都可能。", ["启动", "点火", "开工", "第一步"], ["点亮芯片", "初始脉冲", "开机标志"], "chip"],
    ["chip-05", 20, "芯片五", "资源不够的时候，合作听起来都像抢。", "竞争、摩擦、争资源。", "内耗、瞎吵、谁也不服。", "你身边最近不是合作氛围，是一群人围着一个插座互相挤。", "团队里每个人都说为了大局，结果全在争接口。", ["抢", "冲突", "资源不够", "团队张力"], ["五块芯片", "主线路", "电流火花"], "chip"],
    ["chip-08", 21, "芯片八", "你不是高效，你是连续发热。", "连续输出、效率提升、忙但有效。", "机械劳动、忙到失去意义。", "你最近的关键词就是：一直在跑，但不确定自己是不是在原地发热。", "你确实产出了很多，也确实没停下来，只是忙碌有时也是遮羞布。", ["高频", "推进", "节奏快", "停不下来"], ["八个脉冲模块", "高速电路", "过热散热片"], "chip"],
    ["chip-10", 22, "芯片十", "做完了，但人也差不多做没了。", "阶段完成、成果落地、终于做完。", "完成过载、收尾痛苦、做完更累。", "事情是做完了，但看你这个脸色，像是把自己也一起提交上去了。", "交付亮起的那一刻，你像一块被反复焊接过的板子，功能还在，灵魂有点糊。", ["封板", "交付", "结果", "代价"], ["完整主板", "十枚芯片", "交付勾选框"], "chip"],
    ["battery-ace", 23, "电池王牌", "你最近有电了，但不保证耐用。", "新关系、新情绪、新能量来源。", "刚有感觉就掉电、续航不足。", "你最近是有心动的，但像刚买来的充电宝，真实电量不好说。", "新的能量、新的喜欢、新的期待，终于不像一具低功耗设备。", ["补能", "心动", "充电", "情绪启动"], ["新电芯", "心跳电流", "电量槽"], "battery"],
    ["battery-02", 24, "电池二", "你们之间是来电，还是漏电，还得再观察。", "互相供电、关系平衡、来电。", "电压不稳、一个人输出太多。", "这张牌说明你们之间是有电流的，就是不知道是爱情，还是漏电。", "两个能量体之间有回应，有互相点亮的可能，关键是电压稳不稳。", ["关系", "配对", "互补", "连接"], ["两颗电池", "稳定电弧", "对称接口"], "battery"],
    ["battery-04", 25, "电池四", "你不是成熟了，你是切省电了。", "保守、休息、低耗能生存。", "麻木、懒得投入、情感待机。", "你不是看破红尘，你只是已经切进省电模式了。", "你不太爱吵、不太爱解释，也不太想投入，这不是顿悟，是低耗能求生。", ["省电模式", "关闭后台", "没劲"], ["省电图标", "暗屏", "关闭后台应用"], "battery"],
    ["battery-09", 26, "电池九", "你看起来正常，是因为低电量提示别人看不见。", "终于接近满电、状态回升。", "透支、虚电、表面正常实则马上关机。", "你现在最适合的不是恋爱，是找个靠谱插头。", "你还能笑、还能上班、还能说我没事，只是这一切都建立在 9% 电量的幻觉上。", ["续航见底", "硬撑", "低电量警告"], ["红色电量格", "警告符号", "近在咫尺的充电线"], "battery"],
    ["battery-10", 27, "电池十", "你终于不再找刺激，开始找插头了。", "关系稳定、情绪完整、家庭感。", "为了稳定而稳定、外表和谐内部空心。", "这张牌是好牌，说明你想要的不是刺激，是有人愿意和你用同一个充电口。", "这是稳定、续航、长期供能。成年人的幸福，有时候就是持续供电。", ["满电", "稳定供能", "长期关系", "温暖"], ["满电阵列", "供能系统", "平稳电流"], "battery"],
    ["laser-03", 28, "激光剑三", "最疼的不是被伤，是终于看懂。", "真相刺痛、关系破口、看清现实。", "纠结、旧伤反复、已经知道还不肯放下。", "你不是突然受伤，你只是终于把那个一直回避的事实看高清了。", "有些真相一直都在，只是你今天终于没有再替它找借口。", ["心碎", "看透", "扎心", "明白但难受"], ["三柄激光剑", "数据心脏", "碎裂图表"], "laser"],
    ["laser-05", 29, "激光剑五", "你赢了逻辑，输了活路。", "争胜、嘴硬、赢了道理输了关系。", "阴阳怪气、低水平消耗。", "你最近不是在沟通，你是在参加一个没人颁奖的辩论赛。", "很多关系在输赢分出来之前就已经没了。", ["对抗", "口舌", "胜负欲", "谁都不服"], ["五柄激光剑", "碎裂对话框", "辩论战场"], "laser"],
    ["laser-07", 30, "激光剑七", "你不是聪明，你是偷感太重。", "策略、藏一手、聪明规避。", "心虚、偷感重、想太多。", "你不是精明，你是每次一做决定，神情都像刚从别人电脑里拔了 U 盘。", "这张牌讲小心思、绕路线、藏一手。太依赖技巧，会活得像浏览器无痕模式。", ["小动作", "绕路", "心眼", "偷偷处理"], ["潜行身影", "数据脚印", "监控死角"], "laser"],
    ["laser-09", 31, "激光剑九", "你没睡着，不代表你在休息。", "焦虑、夜里想太多、精神过载。", "终于崩完、开始面对现实。", "你晚上不是睡不着，你是脑子里有 47 个网页标签没关。", "躺下去的是身体，开机的是大脑。深夜弹窗像审判一样围过来。", ["失眠", "脑内弹窗", "内耗", "停不下来"], ["床边人物", "九道信息光刃", "未读弹窗"], "laser"],
    ["disk-04", 32, "硬盘币四", "你不是会存钱，你是害怕流动。", "保守、守财、求稳、资源防御。", "抓太紧、不流动、越怕失去越失去。", "你不是抠，你只是在人生里长期处于存储空间不足，请谨慎使用。", "你紧紧抓着现有的一切。资源一旦变成盔甲，人就很难拥抱什么。", ["囤", "守", "资产", "防御姿态"], ["四枚硬盘币", "机械储存盒", "数据仓库"], "disk"],
    ["disk-06", 33, "硬盘币六", "借出去的是资源，回来的通常是人情。", "资源流动、互相支持、收支平衡。", "人情债、给得不均、交换不对等。", "你最近的钱和感情有点像共享充电宝：借出去容易，回来挺难。", "你和别人之间有很多能量往来，只是这种流动不一定对等。", ["给与拿", "资源配置", "平衡", "支援"], ["六枚硬盘币", "天平", "资源管道"], "disk"],
    ["disk-08", 34, "硬盘币八", "成长很多时候，长得就像上班。", "打磨技能、苦练、靠手艺吃饭。", "重复劳动、只会埋头干、不抬头看方向。", "这张牌说明你不是没前途，你只是正在一个很像坐牢的成长阶段。", "没什么戏剧性，也没什么掌声，但你确实一点点变强。", ["练习", "专业", "工匠", "长期积累"], ["打磨硬盘币", "工作台", "版本演进"], "disk"],
    ["disk-10", 35, "硬盘币十", "稳定到了这一步，就该轮到你怀疑人生了。", "长期稳定、资产积累、现实落地。", "被现实绑住、稳定但不快乐。", "这张牌说明你是有机会稳下来的，只不过现代人一稳定，就容易怀疑自己是不是老了。", "这是积累、家底、长期、现实落地。你不是没有得到，只是不习惯拥有。", ["存量", "长期", "家底", "安全盘"], ["十枚硬盘币", "数据城邦", "成熟系统"], "disk"],
    ["easter-intern", 36, "实习生", "你的真诚，暂时还没长出经验。", "有热情、有新鲜感、什么都敢试。", "经验不足、容易闯祸、努力得很明显。", "你处理人生问题的方式，像一个第一天入职但很有礼貌的人。", "这张牌很可爱，也很危险。现实不总奖励真诚，它有时只奖励少犯错。", ["萌新", "学习", "热情", "手忙脚乱"], ["电脑", "工牌", "教程", "问号"], "easter"],
    ["easter-engineer", 37, "工程师", "你不是不懂感情，你只是想先定位问题。", "执行、死磕、解决问题。", "沟通差、情绪钝、只想修 bug 不想聊感受。", "你其实挺可靠，就是谈感情的时候，像在给别人做故障排查。", "你做事靠谱，遇事先修。别人想被理解时，你已经开始排查故障了。", ["实现", "修复", "逻辑", "实干"], ["发光工具", "调试终端", "bug 图标"], "easter"],
    ["easter-scientist", 38, "首席科学家", "你不是难接近，你只是像在答辩。", "成熟判断、看得远、掌控复杂局面。", "高冷、脱离现实、聪明得没人敢靠近。", "你不是难相处，你只是每次一认真起来，别人都像在参加答辩。", "你看得远，逻辑强，脑子很值钱。副作用是周围人自动觉得自己要交 PPT。", ["战略", "远见", "复杂", "掌控"], ["全息模型", "公式", "知识穹顶"], "easter"],
    ["easter-vc", 39, "风投", "你不是爱他，你是觉得他有想象空间。", "押注未来、敢赌机会、愿意冒险。", "虚高、画饼、烧钱无回报。", "你对这段关系的态度不像恋爱，像在做早期项目投资。", "你容易先看增长曲线，不一定想要现在的好，而是未来可能的爆。", ["投资", "想象空间", "赌性", "回报周期"], ["资本光束", "上涨曲线", "融资环"], "easter"],
    ["easter-powerbank", 40, "共享充电宝", "他不是你的归宿，他只是你今天的 20%。", "短暂救命、及时支持、互相补给。", "依赖、昂贵、离开就没电。", "有些人出现在你生命里，不是来陪你一生的，是来让你先撑到地铁口的。", "有些人出现得很及时，陪你撑过一小段。问题是他们从一开始就写着按时归还。", ["临时补能", "依附", "借用", "短续航"], ["共享充电站", "租借计时", "夜晚街头"], "easter"]
  ].map(([id, order, name, subtitle, uprightMeaning, reversedMeaning, stageLine, description, aiKeywords, imageElements, group]) =>
    makeCard({
      id: id as string,
      order: order as number,
      name: name as string,
      subtitle: subtitle as string,
      group: group as CardGroup,
      tags: aiKeywords as string[],
      uprightMeaning: uprightMeaning as string,
      reversedMeaning: reversedMeaning as string,
      aiKeywords: aiKeywords as string[],
      stageLine: stageLine as string,
      description: description as string,
      imageElements: imageElements as string[],
      visualStyle: "赛博神谕风，中心主体、神秘学边框、科技光效。"
    })
  )
];

export const getPublishedCards = () => initialCards.filter((card) => card.isPublished);

export const findCardById = (id: string) => initialCards.find((card) => card.id === id);

export const getGroupLabel = (group: CardGroup) => groupMeta[group].category;
